const cars=[
{id:'yaris',cat:'sedan',year:2019,nameAr:'تويوتا يارس',nameEn:'Toyota Yaris',descAr:'سيارة عملية واقتصادية واعتمادية، مناسبة للاستخدام اليومي.',descEn:'A practical, economical and dependable sedan for everyday driving.',images:['yaris-cover.jpeg','yaris-1.jpeg','yaris-2.jpeg','yaris-3.jpeg','yaris-4.jpeg','yaris-5.jpeg'],plans:[{down:600,month:160,term:24}]},
{id:'versa2019',cat:'sedan',year:2019,nameAr:'نيسان فيرسا',nameEn:'Nissan Versa',descAr:'نيسان فيرسا 2019 بنظام تقسيط مريح.',descEn:'Nissan Versa 2019 with a convenient installment plan.',images:['versa2019-cover.jpeg'],plans:[{down:600,month:165,term:12}]},
{id:'versa',cat:'sedan',year:2021,nameAr:'نيسان فيرسا',nameEn:'Nissan Versa',descAr:'سيدان عصرية مريحة مع خيارين للتقسيط.',descEn:'A modern comfortable sedan with two payment options.',images:['versa2021-cover.jpeg','versa-1.png','versa-2.jpeg','versa-3.jpeg','versa-4.jpeg','versa-5.jpeg','versa-ad.jpeg'],plans:[{down:650,month:250,term:12},{down:1000,month:165,term:12}]},
{id:'elantra',cat:'sedan',year:2019,nameAr:'هيونداي إلنترا',nameEn:'Hyundai Elantra',descAr:'تصميم أنيق وتجربة قيادة مريحة مع عروض تقسيط مرنة.',descEn:'Stylish design and comfortable driving with flexible payment plans.',images:['elantra-cover.jpeg','elantra-1.png','elantra-2.png','elantra-3.png','elantra-4.jpeg','elantra-5.jpeg','elantra-6.jpeg','elantra-7.jpeg','elantra-8.jpeg','elantra-ad.jpeg'],plans:[{down:650,month:250,term:12},{down:1000,month:165,term:12}]},
{id:'i10',cat:'sedan',year:2019,nameAr:'هيونداي i10',nameEn:'Hyundai i10',descAr:'سيارة اقتصادية مدمجة وسهلة للاستخدام داخل المدينة.',descEn:'A compact economical car that is easy to use in the city.',images:['i10-1.jpeg','i10-2.jpeg','i10-3.jpeg','i10-ad.jpeg'],plans:[{down:500,month:160,term:12},{down:500,month:120,term:24}]},
{id:'pathfinder',cat:'suv',year:2016,nameAr:'نيسان باثفايندر',nameEn:'Nissan Pathfinder',descAr:'سيارة SUV واسعة وعملية مع خيارين للتقسيط.',descEn:'A spacious practical SUV with two payment options.',images:['pathfinder-cover.jpeg','pathfinder-ad.png','pathfinder-1.jpeg','pathfinder-2.jpeg','pathfinder-3.jpeg','pathfinder-4.jpeg'],plans:[{down:1000,month:250,term:12},{down:1000,month:175,term:24}]},
{id:'expert',cat:'commercial',year:2019,nameAr:'بيجو إكسبيرت',nameEn:'Peugeot Expert',descAr:'فان تجاري عملي بمساحة تخزين واسعة للاستخدامات التجارية.',descEn:'A practical commercial van with generous cargo space for business use.',images:['expert-cover.jpeg','expert-1.jpeg','expert-ad.jpeg','expert-2.jpeg','expert-3.jpeg'],plans:[{down:550,month:320,term:12}]}
];
let lang='ar',activeFilter='all',currentCar=null,currentImage=0;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function t(ar,en){return lang==='ar'?ar:en}function money(n){return new Intl.NumberFormat(lang==='ar'?'ar-OM':'en-OM').format(n)}
function renderCars(){const grid=$('#carGrid');grid.innerHTML='';cars.filter(c=>activeFilter==='all'||c.cat===activeFilter).forEach((c,i)=>{const p=c.plans[0];const el=document.createElement('article');el.className='car-card reveal';el.innerHTML=`<div class="car-photo"><img src="assets/images/${c.images[0]}" alt="${lang==='ar'?c.nameAr:c.nameEn}"><span class="car-badge">${c.year}</span></div><div class="car-body"><h3>${lang==='ar'?c.nameAr:c.nameEn}</h3><p>${lang==='ar'?c.descAr:c.descEn}</p><div class="mini-plan"><div><b>${money(p.down)} OMR</b><span>${t('المقدم','Down')}</span></div><div><b>${money(p.month)} OMR</b><span>${t('شهرياً','Monthly')}</span></div><div><b>${p.term}</b><span>${t('شهر','Months')}</span></div></div><div class="view-link">${t('عرض التفاصيل ←','View details →')}</div></div>`;el.addEventListener('click',()=>openModal(c));grid.appendChild(el);setTimeout(()=>el.classList.add('in'),80+i*70)});}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.classList.toggle('en',lang==='en');$('#langBtn').textContent=lang==='ar'?'EN':'ع';$$('[data-ar]').forEach(el=>el.textContent=el.dataset[lang]);renderCars();if(currentCar)fillModal(currentCar)}
function fillModal(c){$('#modalYear').textContent=c.year;$('#modalTitle').textContent=lang==='ar'?c.nameAr:c.nameEn;$('#modalDesc').textContent=lang==='ar'?c.descAr:c.descEn;$('#modalPlans').innerHTML=c.plans.map((p,i)=>`<div class="plan"><div class="plan-head">${t(c.plans.length>1?`الخيار ${i+1}`:'عرض التقسيط',c.plans.length>1?`Option ${i+1}`:'Payment plan')}</div><div class="plan-grid"><div><b>${money(p.down)} OMR</b><span>${t('المقدم','Down payment')}</span></div><div><b>${money(p.month)} OMR</b><span>${t('القسط الشهري','Monthly')}</span></div><div><b>${p.term}</b><span>${t('شهر','Months')}</span></div></div></div>`).join('');$('#modalWa').textContent=t('اسأل عن السيارة','Ask about this car');const msg=encodeURIComponent(`${t('مرحباً، أريد الاستفسار عن','Hello, I would like to ask about')} ${lang==='ar'?c.nameAr:c.nameEn} ${c.year}`);$('#modalWa').href=`https://wa.me/96899091203?text=${msg}`;renderImage()}
function openModal(c){currentCar=c;currentImage=0;fillModal(c);$('#carModal').classList.add('open');$('#carModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){$('#carModal').classList.remove('open');$('#carModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function renderImage(){if(!currentCar)return;$('#modalMain').src=`assets/images/${currentCar.images[currentImage]}`;$('#thumbs').innerHTML=currentCar.images.map((im,i)=>`<img class="thumb ${i===currentImage?'active':''}" src="assets/images/${im}" data-i="${i}" alt="">`).join('');$$('.thumb').forEach(x=>x.onclick=()=>{currentImage=+x.dataset.i;renderImage()})}
$('#prevImg').onclick=()=>{if(currentCar){currentImage=(currentImage-1+currentCar.images.length)%currentCar.images.length;renderImage()}};$('#nextImg').onclick=()=>{if(currentCar){currentImage=(currentImage+1)%currentCar.images.length;renderImage()}};$$('[data-close]').forEach(x=>x.onclick=closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$('#langBtn').onclick=()=>{lang=lang==='ar'?'en':'ar';applyLang()};$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$$('.nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderCars()});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});$$('.reveal').forEach(x=>io.observe(x));window.addEventListener('scroll',()=>$('.topbar').classList.toggle('scrolled',scrollY>20));
renderCars();setTimeout(()=>$('#intro').classList.add('hide'),2450);
